FROM continuumio/miniconda3:latest
MAINTAINER 4A7G0029@stust.edu.tw

WORKDIR Graduation-Project
COPY CPC-MaskRCNN.yml ./
RUN conda update conda -y
#RUN conda env update --name base --file CPC-MaskRCNN.yml --prune
